services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: ha-dev
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
    environment:
      - TZ=America/New_York
